const SET_BEERS_DATA = "SET_DATA";
const SET_BEERS_PAGE = "SET_PAGE";
const SET_BEERS_MODE = "SET_MODE";
const SET_BEERS_SEARCH = "SET_SEARCH";
const SET_BEERS_OPTIONS = "SET_BEERS_OPTIONS";
const SET_BEERS_ID = "SET_BEERS_ID";

export {
  SET_BEERS_DATA,
  SET_BEERS_PAGE,
  SET_BEERS_MODE,
  SET_BEERS_SEARCH,
  SET_BEERS_OPTIONS,
  SET_BEERS_ID,
};
